Radius: 6000

Cooldown: 30

Autostart: true

Worlds:
  - world
Crates:
  Normal:
    Name: "NORMAL"
    Hologram: "-------------\nNormal Crate\n-------------"
    Chance: 90
    Speed: 1
    Price: 1000
    Rewards:
      Diamond_Sword:
        Name: "TNT"
        Lore: "THIS IS A TNT"
        Chance: 10
        Enchantments:
          Sharpness: 1
          Unbreaking: 2
      Potion:
        Name: "REGEN"
        Lore: "HEAL ME"
        Chance: 30
        Effects:
          Regen:
            Duration: 60
            Multiplier: 4
          Speed:
            Duration: 60
            Multiplier: 5
      Splash_Potion:
        Name: "DIE DIE"
        Lore: "Your dead to me"
        Chance: 50
        Effects:
          Harm:
            Duration: 10
            Multiplier: 10
          Poison:
            Duration: 10
            Multiplier: 10
  Epic:
    Name: "EPIC"
    Hologram: "-------------\nNormal Crate\n-------------"
    Chance: 10
    Speed: 0.1
    Price: 100000
    Rewards:
      Diamond_Chestplate:
        Name: "ARMOR"
        Lore: "THIS IS A TNT"
        Chance: 50
        Enchantments:
          Protection: 1
          Unbreaking: 2