Radius: 6000

Cooldown: 30

Autostart: true

Worlds:
  - world
Crates:
  Normal:
    Name: "NORMAL"
    Percentage: 90
    Speed: 1
    Rewards:
      Diamond_Sword:
        Name: "TNT"
        Lore: "THIS IS A FUCKING TNT"
        Percentage: 10
        Enchantments:
          Sharpness: 1
          Unbreaking: 2
      Potion:
        Name: "REGEN BITCHES"
        Lore: "HEAL ME BITCH"
        Percentage: 30
        Effects:
          Regen:
            Duration: 60
            Multiplier: 4
          Speed:
            Duration: 60
            Multiplier: 5
      Splash_Potion:
        Name: "DIE DIE"
        Lore: "Your dead to me"
        Percentage: 50
        Effects:
          Harm:
            Duration: 10
            Multiplier: 10
          Poison:
            Duration: 10
            Multiplier: 10
