main: me.mmigas.SupplyCrate
name: SupplyCrate
description: A simple event plugin
api-version: 1.16
version: 1.0
softdepend: [WorldGuard, WorldEdit, GriefPrevention, Vault]

commands:
  crate:
    description: Crate commands

permissions:
  supplycrate.buy:
    default: op
  supplycrate.cleanup:
    default: op
  supplycrate.info:
    default: true
  supplycrate.help:
    default: true
  supplycrate.spawn:
    default: op
  supplycrate.start:
    default: op
  supplycrate.stop:
    default: op
  supplycrate.timer:
    default: op
