main: me.mmigas.SupplyCrate
name: SupplyCrate
description: A simple event plugin
api-version: 1.16
version: 1.0
softdepend: [WorldGuard, WorldEdit, GriefPrevention]

commands:
  crate:
    description: Crate commands

permissions:
  supplydrop.buy:
    default: op
  supplydrop.cleanup:
    default: op
  supplydrop.info:
    default: true
  supplydrop.help:
    default: true
  supplydrop.spawn:
    default: op
  supplydrop.start:
    default: op
  supplydrop.stop:
    default: op
  supplydrop.timer:
    default: op
