main: me.mmigas.EventSystem
name: EventSystem
description: A simple event plugin
api-version: 1.16
version: 1.0

softdepend: [WorldGuard, WorldEdit, GriefPrevention]

commands:
  crate:
    description: Crate commands

permissions:
  eventSystem.spawncrate:
    default: op
  eventSystem.startcrate:
    default: op
  eventSystem.stopcrate:
    default: op
